# Generated by Django 4.1.3 on 2023-11-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cnic',
            field=models.BigIntegerField(null=True),
        ),
    ]
