# Generated by Django 4.1.3 on 2024-01-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_worker_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='cnic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cnic',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
