# Generated by Django 4.1.3 on 2024-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_client_cnic_remove_worker_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
