# Generated by Django 4.1.3 on 2024-01-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='base_rating',
            field=models.IntegerField(default=1300),
        ),
        migrations.AlterField(
            model_name='worker',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
