# Generated by Django 4.1.3 on 2024-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_worker_base_rating_alter_worker_task_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='workerType',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Goldsmith', 'Goldsmith'), ('Blacksmith', 'Blacksmith'), ('Other', 'Other')], max_length=20),
        ),
    ]
