# Generated by Django 4.2.5 on 2023-11-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0003_alter_task_client_alter_task_worker'),
        ('user', '0003_alter_worker_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_to_worker', models.CharField(max_length=15, null=True)),
                ('feedback_to_user', models.CharField(max_length=300, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.worker')),
            ],
        ),
    ]
