# Generated by Django 4.2.6 on 2023-10-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_worker_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('TaskPost', 'TaskPosted'), ('TaskAccept', 'TaskAccepted'), ('TaskProcessing', 'TaskProcessing'), ('TaskDeclined', 'TaskDeclined'), ('TaskCompleted', 'TaskCompleted')], default='TaskPosted', max_length=20)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.address')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.worker')),
            ],
        ),
    ]
