# Generated by Django 4.2.6 on 2023-10-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_worker_cnic'),
        ('task', '0002_task_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client'),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.worker'),
        ),
    ]
