# Generated by Django 4.1.3 on 2024-01-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_worker_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
