# Generated by Django 4.2.6 on 2023-10-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskType',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Goldsmith', 'Goldsmith'), ('Blacksmith', 'Blacksmith'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
