# Generated by Django 4.1.3 on 2023-11-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_client_alter_task_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker_response',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
