# Generated by Django 4.2.6 on 2023-10-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_phone_alter_worker_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cnic',
            field=models.BigIntegerField(null=True),
        ),
    ]
