# Generated by Django 4.1.3 on 2023-12-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_worker_response'),
        ('notifications', '0002_tasknotification_worker_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknotification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', unique=True),
        ),
    ]
