# Generated by Django 4.1.3 on 2023-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_tasknotification_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tasknotification',
            name='task',
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
